name: AdminPerms
main: de.Lathanael.AdminPerms.bukkit.Main
version: ${project.version} (BUILD ${git.build.time})
author: Lathanael
authors: [Lathanael]
description: AdminPerms provides permissions in a simple true/false scheme and some additional player-metainformation

commands:
  ap_check:
    aliases: [permcheck, pcheck]
    description: check if a player or the sender has a permission (any plugin).
    usage: /<command> <node> [player]
  ap_dump:
    aliases: [permdump, pdump]
    description: Prints info about a player's (or the sender's) permissions.
    usage: /<command> [player] [page]
  ap_info:
    aliases: [perminfo, pinfo]
    description: Prints information on a specific permission.
    usage: /<command> <node> 
  ap_reload:
    aliases: [permreload, preload]
    description: Reload the plugin(includes configuration and permissions)
    usage: /<command>
  ap_rank:
    aliases: [permrank, prank]
    description: Promote or demote a player.
    usage: |
        /<command> <pro(mote)> <player>
        /<command> <de(mote)> <player>
  ap_player:
    aliases: [permplayer, pplayer]
    description: check if a player or the sender has a permission (any plugin).
    usage: |
        /<command> groups <player> - list groups a player is in.
        /<command> setgroup <player> <group,...> - set a player to be in only the given groups.
        /<command> addgroup <player> <group,...> - add a player to a group.
        /<command> removegroup <player> <group,...> - remove a player from a group.
        /<command> setperm <player> <[world:]node> [true|false] - set a permission on a player.
        /<command> unsetperm <player> <[world:]node> - unset a permission on a player.
  ap_group:
    aliases: [permgroup, pgroup]
    description: check if a player or the sender has a permission (any plugin).
    usage: |
        /<command> list - list all groups.
        /<command> players <group> - list players in a group.
        /<command> setperm <group> <[world:]node> [true|false] - set a permission on a group.
        /<command> unsetperm <group> <[world:]node> - unset a permission on a group.

permissions:
  adminperms.*:
    default: op
    description: Allows use of all AdminPerms administration commands.
    children:
      adminperms.reload: true
      adminperms.check: true
      adminperms.info: true
      adminperms.dump: true
      adminperms.rank: true
      adminperms.group.*: true
      adminperms.player.*: true
  adminperms.rank:
    description: Allos use of /permrank.
  adminperms.build:
    description: Allows player to build.
    default: true
  adminperms.reload:
    description: Allows use of /permreload.
  adminperms.check:
    description: Allows use of /permcheck.
  adminperms.info:
    description: Allows use of /perminfo.
  adminperms.dump:
    description: Allows use of /permdump.
  adminperms.group.*:
    description: Allows use of all /permgroup commands.
    children:
      adminperms.group.list: true
      adminperms.group.players: true
      adminperms.group.setperm: true
      adminperms.group.unsetperm: true
  adminperms.group.list:
    description: Allows use of /permgroup list.
  adminperms.group.players:
    description: Allows use of /permgroup players.
  adminperms.group.setperm:
    description: Allows use of /permgroup setperm.
  adminperms.group.unsetperm:
    description: Allows use of /permgroup unsetperm.
  adminperms.player.*:
    description: Allows use of all /permplayer commands.
    children:
      adminperms.player.groups: true
      adminperms.player.setgroup: true
      adminperms.player.addgroup: true
      adminperms.player.removegroup: true
      adminperms.player.setperm: true
      adminperms.player.unsetperm: true
  adminperms.player.groups:
    description: Allows use of /permplayer groups.
  adminperms.player.setgroup:
    description: Allows use of /permplayer setgroup.
  adminperms.player.addgroup:
    description: Allows use of /permplayer addgroup.
  adminperms.player.removegroup:
    description: Allows use of /permplayer removegroup.
  adminperms.player.setperm:
    description: Allows use of /permplayer setperm.
  adminperms.player.unsetperm:
    description: Allows use of /permplayer unsetperm.